### ISSUE TITLE
Sorting out dependencies

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/numericalsgps#7] opened 2017-09-15 23:34 UTC
This has been triggered by the problem in running a test on a machine where the Singular CAS is not available. The singular package is loadable (since is has `AvailabilityTest := ReturnTrue`), but when one tries to execute the test, the following happens:
```
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-sta\
ble-snapshot/tst/teststandard/bugfix.tst, line 1103:
# Input is:
ReducedGroebnerBasis(L,MonomialLexOrdering([x_1,x_2,x_3,x_4,x_5]));
# Expected output:
[ x_4^2+x_5^2-1, -x_3*x_4+x_5^2+x_2-1, -x_3*x_5-x_4*x_5+x_1 ]
# But found:
  Type 'sing_exec:="<path>"; return;' where <path>
  is the path of the Singular executable file on your system.
  'sing_exec' must be a string.
Error, Singular executable file not found!

########
```
This happens only if Singular is loaded before NumericalSgps. Otherwise, the example works fine:
```
gap> LoadPackage("numeric");
#I  Please load package NormalizInterface or 4ti2Interface
#I  to have extended functionalities.
#I  Please load package SingularInterface or singular (not both)
#I  or GradedModules to have extended functionalities.
----------------------------------------------------------------
Loading  NumericalSgps 1.1.2
For help, type: ?NumericalSgps: 
----------------------------------------------------------------
true
gap> x_1:=X(Rationals,"x_1":old);;
gap> x_2:=X(Rationals,"x_2":old);;
gap> x_3:=X(Rationals,"x_3":old);;
gap> x_4:=X(Rationals,"x_4":old);;
gap> x_5:=X(Rationals,"x_5":old);;
gap> L:=[(x_3+x_4)*x_5-x_1,(x_3+x_4)*x_4-x_2,x_5^2+x_4^2-1];;
gap> ReducedGroebnerBasis(L,MonomialLexOrdering([x_1,x_2,x_3,x_4,x_5]));
[ x_4^2+x_5^2-1, -x_3*x_4+x_5^2+x_2-1, -x_3*x_5-x_4*x_5+x_1 ]
gap> 
```
A workaround would be to check in NumericalSgps whether `Singular` command is available and do not use Singular if it is not. Also, why not to make a number of packages suggested for NumericalSgps?

**Comment by pedritomelenas** [comment] 2017-09-16 06:58
The problem is that singular loads even if singular cas is not available, or if it is not in the path. Numericalsgps tries to use it whenever it is loaded. We could probably try to check for availability of the executable. 
We set singular to make Gröbner bases calculations, whenever available.
A user willing to take the advantage  of singular should have first it properly set in their system.
Thanks

**Comment by pedritomelenas** [comment] 2017-12-18 22:53
Fixed in https://github.com/gap-packages/numericalsgps/commit/0a31cfa3f01566b15f777b879a70b7294a4bd203

**Closed by pedritomelenas** 2017-12-18 22:53 UTC
