### ISSUE TITLE
SmallElementsOfNumericalSemigroup reports an error 

### ISSUE THREAD

**Issue by alfsan** [gap-packages/numericalsgps#58] opened 2020-09-07 16:12 UTC
with the following example:
```
gap> interv:=[13/10, 7/5];;
gap> s:=NumericalSemigroupByInterval(interv);
<Proportionally modular numerical semigroup satisfying 70x mod 91 <= 5x >
gap> SmallElementsOfNumericalSemigroup(s);
Error, Range: <last> must be an integer less than 2^60 (not a rational) in
  gaps := Difference( [ 1 .. k * s ], smalls )
 ; at /home/alfredo/lib/gap-4.10.1/pkg/NumericalSgps-1.1.10/gap/elements.gi:126 called from 
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:6
you can replace <last> via 'return <last>;'
```
`k = 13` and `s = 7/5` in his case, so using `CeilingOfRational` in line 126 and 133 avoids the problem.

Please let me know if I am misusing the function.

**Comment by ManuelAFDelgado** [comment] 2020-09-09 16:44
Alfredo: thank you very much for letting us know this problem. And thank you for pointing out a solution. 
The issue is fixed in commit fa5e9b8.

**Closed by ManuelAFDelgado** 2020-09-09 16:44 UTC
